---

# Install Kibana Plugins
#
# You will need to define an array called 'kibana_plugins' in your playbook or inventory, such that:
#
# kibana_plugins:
#  - { name: '<plugin name>', url: '<[optional] plugin url>' }
#  - ...
# where if you were to install the plugin via bin/kibana, you would type:
#
# bin/kibana plugin --install <plugin name>
#
# or
#
# bin/kibana plugin --install <plugin name> --url <plugin url>

# Loop though kibana_plugins and install them

# - name: Removing Old Plugins
#   shell: "bin/kibana plugin --remove {{ item.name }}"
#   args:
#     chdir: "{{ kibana_home_dir }}"
#   when: item.name is defined and item.reinstall is defined and item.reinstall == True
#   with_items: "{{ kibana_plugins }}"
#   ignore_errors: yes
  
- name: Installing Plugins
  shell: "bin/kibana-plugin install {{ item }}"
  args:
    chdir: "{{ kibana_home_dir }}"
    creates: "{{ kibana_home_dir }}/plugins/{{ item }}" # dubious?
  with_items: "{{ kibana_plugins }}"
  notify:
    - restart kibana
  register: kibana_plugins_installed
  changed_when: "{{ 'Installed' in kibana_plugins_installed.stdout }}"
  failed_when:  "{{ kibana_plugins_installed.rc != 0 and 'already exists' not in kibana_plugins_installed.stderr }}"
